---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: <nome-aluno>
type: Opaque
data:
  username: am9u
  password: am9uZXM=

---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: <nome-aluno>
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret



---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  username: am9u
  password: am9uZXM=

---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: default
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret